### ISSUE TITLE
Not an issue, but rather an addition

### ISSUE THREAD

**Issue by jofor** [konmik/nucleus#1]
Just a small addition to be able to use the new toolbar from materialdesign.
Adds NucleusActionBarActivity as class :)

https://gist.github.com/jofor/b73e2d9215f04d4ca784

**Comment by konmik** [comment]
Ok, I will split the library into three:

* nucleus (NucleusActivity, NucleusFragment, NucleusLayout)
* nucleus-support-v4 (for NucleusSupportFragment, NucleusFragmentActivity)
* nucleus-support-v7 (for NucleusActionBarActivity)

Check out 1.0.1 release soon.

P.S. Now I finally understood why Square guys didn't want to make View classes :D

**Comment by konmik** [comment]
Done!

1.1.0 release in fact
