### ISSUE TITLE
[Question] - Use same presenter for multiple Fragments

### ISSUE THREAD

**Issue by cavarzan** [konmik/nucleus#10]
Hi!

I'm starting to implement the library now, but I have a question for reuse of fragments.

Let me explain my doubt:

Considering I have two fragments, one is a map, and another a list, put into a ViewPager. Can I use the same presenter in two fragments to reuse the API calls? In this hypothetical example both fragments query for the same data in API.

Or the best approach is use the Activity presenter to query the data and than delivery to the fragments?

It's just a question about architecture and things that I can archieve using the library, fell free to close this issue if you think is off-topic.

And thanks for the amazing project.

**Comment by konmik** [comment]
Hi,

I would create a separate singleton that calls api and use that singleton in both presenters.

Welcome :)
