### ISSUE TITLE
What is best way to use multiple presenters within a fragment?

### ISSUE THREAD

**Issue by sinha-abhishek** [konmik/nucleus#102]
Most examples use annotation RequirePresenter to bind a presenter to one fragment which in turn extends from NucleusFragment. However, let's say I have a fragment which can be conceptually split into multiple views and which could be populated by one presenter each. Is there any current way to do it. We can like make a Presenter object inside each sub-view and pass on all Fragment Lifecycle events to it but that may become prone to error in case one of lifecycle events are not passed to presenter. Is there any thing already present within nucleus which can handle such scenario or will we need an implementation something like I mentioned before

**Comment by konmik** [comment]
https://github.com/konmik/nucleus/issues/89
