### ISSUE TITLE
Why is getPresenter() public and not protected?

### ISSUE THREAD

**Issue by sreejithraman** [konmik/nucleus#105]
This may be a silly question... But if only the view should have access to the presenter, why not make it protected so that view implementation detail objects can't use them? For example, if I pass in the activity to the adapter, shouldn't its presenter be hidden to the adapter?

**Comment by konmik** [comment]
Do you mean,, the `getPresenter()` method? This is a matter of style. I prefer to use "protected" keyword only for methods that need to be overridden. This is a very old convention, from C++ times. It helps to compose code in many ways.

**Comment by TWiStErRob** [comment]
@sreejithraman why would you pass in a typed `BlahActivity` into the adapter or cast `view.getContext()`?
@konmik a middle ground may be `protected final P getPresenter()`? It signifies "it's only for children", but "don't mess with it too much".

**Comment by sreejithraman** [comment]
@TWiStErRob Lets say you have something like a FB newsfeed and you press "Like" on one of the items. Then you need to get the activity to tell the presenter to like an item. Am I thinking about this the wrong way?

**Comment by TWiStErRob** [comment]
@sreejithraman ah, in that case I usually define an inner interface in the adapter and pass in an implementation in the constructor (which can be the activity itself or an inner class of it). When the onClick listener registered in the viewholder's view notices a click to the like button, it delegates to that object received in the constructor and then the interface implementation can call the presenter.

**Comment by konmik** [comment]
@TWiStErRob There is no reason to prohibit something. By prohibiting things we lose composability.

For example, you will not be able to call presenter from ViewHolder or from dialogs, sometimes this can help to cut a lots of corners. Also, when you make something protected it immediately becomes very hard to test.
