### ISSUE TITLE
when i confound app，occur some questions

### ISSUE THREAD

**Issue by ruhaly** [konmik/nucleus#107]
when i confound app，occur some questions
11java.lang.RuntimeException: java.lang.InstantiationException: can't instantiate class com.luichi.ygj.a.cf; no empty constructor
                                                     java.lang.InstantiationException: can't instantiate class com.luichi.ygj.a.cf; no empty constructor
                                                     nucleus.factory.ReflectionPresenterFactory.createPresenter(Unknown Source)
                                                     nucleus.view.PresenterLifecycleDelegate.getPresenter(Unknown Source)
                                                     nucleus.view.PresenterLifecycleDelegate.onResume(Unknown Source)
                                                     nucleus.view.NucleusSupportFragment.onResume(Unknown Source)
                                                     com.luichi.ygj.base.BaseFragment.onResume(Unknown Source)
                                                     android.support.v4.app.Fragment.performResume(Unknown Source)
                                                     android.support.v4.app.FragmentManagerImpl.moveToState(Unknown Source)
                                                     android.support.v4.app.FragmentManagerImpl.moveToState(Unknown Source)
                                                     android.support.v4.app.BackStackRecord.run(Unknown Source)
                                                     android.support.v4.app.FragmentManagerImpl.execPendingActions(Unknown Source)
                                                     android.support.v4.app.FragmentManagerImpl.executePendingTransactions(Unknown Source)
                                                     android.support.v4.app.FragmentPagerAdapter.finishUpdate(Unknown Source)
                                                     android.support.v4.view.ViewPager.populate(Unknown Source)
                                                     android.support.v4.view.ViewPager.populate(Unknown Source)
                                                     android.support.v4.view.ViewPager.onMeasure(Unknown Source)
                                                     android.view.View.measure(View.java:16508)
                                                     android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
                                                     android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
                                                     android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
                                                     android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
                                                     android.view.View.measure(View.java:16508)
                                                     android.support.v4.view.ViewPager.onMeasure(Unknown Source)
                                                     android.view.View.measure(View.java:16508)
                                                     android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
                                                     android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
                                                     android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
                                                     android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
                                                     android.view.View.measure(View.java:16508)
                                                     android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
                                                     android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                                                     android.view.View.measure(View.java:16508)
                                                     android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
                                                     android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                                                     android.support.v7.widget.ContentFrameLayout.onMeasure(Unknown Source)
                                                     android.view.View.measure(View.java:16508)
                                                     android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
                                                     android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
                                                     android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
                                                     android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
                                                     android.view.View.measure(View.java:16508)
                                                     android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
                                                     android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                                                     android.view.View.measure(View.java:16508)
                                                     android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
                                                     android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
                                                     android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
                                                     android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
                                                     android.view.View.measure(View.java:16508)
                                                     android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
                                                     android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
                                                     com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2291)
                                                     android.view.View.measure(View.java:16508)
                                                     android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2003)
                                                     android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1200)
                                                     android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1382)
                                                     android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1087)
                                                     android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5696)
                                                     android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
                                                     android.view.Choreographer.doCallbacks(Choreographer.java:574)
                                                     android.view.Choreographer.doFrame(Choreographer.java:544)
                                                     android.view.Choreographer
08-19 13:58:04.635 3210-3210/? I/egj-YGJApplication: exitApp()

**Comment by konmik** [comment]
Can it be because you have no empty constructor? :D

I do not see how it is related to nucleus yet.
