### ISSUE TITLE
RxJava2 Support

### ISSUE THREAD

**Issue by Dev-iL** [konmik/nucleus#111]
Hello Konstantin,

Do your long-term plans for the library include the adoption of [RxJava v2](https://github.com/ReactiveX/RxJava/tree/2.x)? It had recently reached RC1, which means the API should be quite stable by now.

If yes, perhaps there's sense in creating another branch of nucleus containing preparations/adaptations for the new RxJava? 

I might be able to help with some _crude_ initial [conversion](https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0) if needed.

**Comment by konmik** [comment]
Hi, feel free to make a pull request.

But I would first wait for the final release.

**Comment by Dev-iL** [comment]
v2 is released as of 3 days ago: https://github.com/ReactiveX/RxJava/releases/tag/v2.0.0

**Comment by konmik** [comment]
great, I will take a look! :)

**Comment by Seidak** [comment]
Hi,
any news about rxjava2 support? :-)

**Comment by konmik** [comment]
I finally decided how to make the transition correctly (and accumulated some experience using rx2 as well). So I target next week for releasing rx2-based artifacts.

**Comment by mptrista** [comment]
Hey @konmik,

Do you need any specific help with this task?

**Comment by konmik** [comment]
Hey, this week I'm releasing the beta. The job is already 90% done, all tests pass.

**Comment by konmik** [comment]
It took longer than expected though. :D

**Comment by konmik** [comment]
Thanks for pinging me, btw!

**Comment by konmik** [comment]
'info.android15.nucleus5:nucleus:5.0.0-beta1' was just released and will be available in a few hours on maven central.

The new package name is nucleus5, branch is https://github.com/konmik/nucleus/tree/rx2.

All examples were updated.

**Comment by konmik** [comment]
Did anyone try it? :D 

Any issues?

Is it ok to mention the build on the main page?

**Comment by Seidak** [comment]
I am really busy this month, I'll definitely try it! And as soon as possible I'll give you feedback

**Comment by gallal** [comment]
Thanks @konmik - I'll try it soon and let you know

**Comment by fmontesino** [comment]
Tested all day long, everything seems fine for me!
Thanks for your work @konmik

**Comment by w00lyc0dy** [comment]
Hi there :)
Thanks for the work @konmik !
Everything works fine, but I have a question regarding the Flowable class: will it be supported for the restartable methods ?

**Comment by sreejithraman** [comment]
any updates on this?

**Comment by konmik** [comment]
No complains so far, use it! :)

**Comment by TWiStErRob** [comment]
@konmik https://github.com/konmik/nucleus/issues/111#issuecomment-293505584 sounds like a complaint ;)

**Comment by konmik** [comment]
I consider flowable to be an optional stream type that is easy to convert into observable. Otherwise we would need to implement restartables for all rxjava stream types, too much of pointless work. You can easily write your own function that will convert stream types you need automatically.

**Comment by Seidak** [comment]
@konmik maybe you should update readme for better orientation for new users.  Instead of 
`compile 'info.android15.nucleus5:nucleus:5.0.0-beta'`
would be better to have there
`compile 'info.android15.nucleus5:nucleus:5.0.0-beta1'`

I am finally going to test the update! :-)

**Comment by Seidak** [comment]
@konmik maybe you should update readme for better orientation for new users. Instead of
compile 'info.android15.nucleus5:nucleus:5.0.0-beta'
would be better to have there
compile 'info.android15.nucleus5:nucleus:5.0.0-beta1'

I am finally going to test the update! :-)

**Comment by shadow7** [comment]
@konmik "I consider flowable to be an optional stream type that is easy to convert into observable". I do not believe this is so simple, the concept of`Flowables` in Rxjava2 allow us to handle the concept of back pressure. Using `.toObeservable()` on these objects converts them into a non-backpressured `Observable`. I agree that this would be arduous work, but not pointless.
