### ISSUE TITLE
Deliver methods

### ISSUE THREAD

**Issue by m-o** [konmik/nucleus#118]
Hi, can you write more about deliverXXX methods, how to use them on their own and when to use/not use restartable? I think i have a usecase when I really do not need restartable. I am changing password on the server, so I just want to call "changePassword" and get view and response as with restartable. Or is my thinking wrong and I should always use restartable? Thanks

**Comment by konmik** [comment]
hi, I would use restartable in this case. What if the app will be disposed from memory during the request? Restartable will restart the request and you will get a response or "wrong password" from your server. If you will not use restartable, the request will be lost and  View will never get an answer.
