### ISSUE TITLE
How to get view in presenter?

### ISSUE THREAD

**Issue by bailyzheng** [konmik/nucleus#120]
In MVP model, view and presenter can known each other. Nucleus can get presenter by getPresenter(). How to get view in presenter class?

**Comment by TWiStErRob** [comment]
How about https://github.com/konmik/nucleus/blob/master/nucleus/src/main/java/nucleus/presenter/Presenter.java#L120 ?

**Comment by yankeppey** [comment]
In my project I use a method in base presenter class

```
    public void deliver(@NonNull Action1<? super View> onNext, @NonNull Action1<Throwable> onError) {
        view().filter(v -> v != null)
                .take(1)
                .subscribe(onNext, onError);
    }
```

which delivers a desired action to View as soon as possible.

**Comment by bailyzheng** [comment]
@yankeppey  right, thank you. I think get view is not recommend in presenter by the author. So view and presenter is decoupling.
