### ISSUE TITLE
Context in presenter for Dagger 2 dependency injection

### ISSUE THREAD

**Issue by BassamHamada** [konmik/nucleus#123]
Hi, Actually it is first time to use both nucleus and dagger 2, so, I just stucked in how to inject objects in presenter while I don have a context to be casted to the application class which has the dagger components that has the ability to inject objects and it is not good to provide and access a static application context, so can you please help me clarifying this.

**Comment by konmik** [comment]
https://github.com/konmik/nucleus/blob/master/nucleus-example-real-life/src/main/java/nucleus/example/ui/base/BaseFragment.java#L18
