### ISSUE TITLE
restartableLatestCache callback to show Popupwindow 

### ISSUE THREAD

**Issue by ml-bright** [konmik/nucleus#129]
Thank you for you library!

When I requestData with method restartableLatestCache and it callback to show a popupwindow success.
but when I rotating screen and then restartableLatestCache callback to show popupwindow , this take exception :  
`unable to add window -- token null is not valid; is your activity running`

it seem that restartableLatestCache callback before onWindowFocusChanged() .

How can i solve this problem

**Comment by zoffl** [comment]
Hi, there is not enough information for me to try troubleshoot this issue. Can you strip your code down to a simple example? Make sure you;re not using NucleusLayout inside of a fragment stack.

**Comment by konmik** [comment]
Hi, there is not enough information for me to try troubleshoot this issue. Can you strip your code down to a simple example? Make sure you;re not using NucleusLayout inside of a fragment stack.

**Comment by ml-bright** [comment]
thank you, it's my problem, i has solve it.
