### ISSUE TITLE
Extract destroy from the PresenterHelper.

### ISSUE THREAD

**Issue by rharter** [konmik/nucleus#13]
Currently, the PresenterHelper class requires the Activity in the `takeView()` method for the sole purpose of determining whether the presenter should be destroyed when dropView is called.

This logic, of deciding whether or not to destroy the presenter should be extracted from the PresenterHelper, completely freeing it from ties to the Activity.

I propose updating the `dropView()` method to something like `dropView(boolean destroy)`.  This way, it's up to the container (ViewGroup, Fragment, Activity, View, Service, etc) to determine when the presenter should be destroyed.

This will better support things like single activity, fragment/view only setups, and ensure the PresenterHelper performs only it's very specific tasks.

**Comment by konmik** [comment]
Hi, what are PresenterHelper specific tasks? :) 
For me this class looks like a collection of shortcuts to not bloat views.
This is why is keeps a reference to an activity.
Do you have a more clear definition for it?

**Comment by rharter** [comment]
My thought was that, aside from the activity reference, this class is a really easy drop-it-anywhere helper for managing a presenter instance.  User's can drop it in any type of class they want to have a managed presenter in, and all of the null safety checks and PresenterManager logic is abstracted.

The problem I see with helper keeping a reference to the activity and managing destroy based on that, is that that's the single piece of this class that prevents it from being general use.  As an example, some project I've inherited use a single Activity model, where all navigation is done using Fragment transactions.  The current PresenterHelper would be of no use there since if presenters were only destroyed when the Activity was finishing, they would never be destroyed until you leave the app.

What I would like to see is the `activity.isFinishing()` moved up to the Nucleus[Activity|Fragment|Layout] base classes as default functionality, thereby making the PresenterHelper a generally reusable class.

I think it's a fairly simple change, and I'm happy to make it if you agree, just wanted to open this ticket to foster discussion.

**Comment by konmik** [comment]
This change will bloat existing classes to some degree, but the ability to reuse the helper looks good. OK.
