### ISSUE TITLE
null bundle onCreate

### ISSUE THREAD

**Issue by cavarzan** [konmik/nucleus#14]
Hello!

Is there any issue with `RxPresenter` that makes the `onCreate(Bundle savedState)` receive the bunde always `null` after orientation changes?

I notice that every time a new Presenter is created, this is causing the `null` `Bundle` at `onCreate`...

![captura de tela 2015-05-05 as 01 22 59](https://cloud.githubusercontent.com/assets/3915288/7467026/b37abd52-f2c5-11e4-9876-77621acb0566.png)

Also, this seems to make the presenter's `deliverLatestCache()` being called several times after the fragment  `onResume` is called.

**Comment by konmik** [comment]
Hello,

No, I'm not aware of such issue. I have a test that ensures that such issue does not exist and RxPresenter works well on production. Do you have an example that can reproduce this behavior?

**Comment by cavarzan** [comment]
@konmik I'll test again tomorrow and follow up you with more info. Basically is a RxPresenter that has a Dagger2 module injected after `onTakeView`. I will take a better look to provide more useful informations about this.
Thanks!

**Comment by konmik** [comment]
I typically get such kind of errors when my View's onSave/onRestore is not properly overloaded.

**Comment by cavarzan** [comment]
@konmik what did you mean with this?

I've checked now and seems that presenter state comes to my fragment, but the presenter doesn't receive that bundle.

I create a gist with the sample of code here:
https://gist.github.com/cavarzan/597b6c618b1f9f339f0d

**Comment by konmik** [comment]
I never used `ViewPager`, but if a fragment gets its bundle, then the presenter should also get its bundle.

Here is an example of `NucleusFragment` usage: (https://github.com/konmik/nucleus/tree/master/nucleus-example-with-fragments)

What your `BasePresenterFragment` does? Does it override `onCreate`/`onSaveInstanceState`? This is how I usually get my errors of such kind - by improperly overriding these methods. :)

**Comment by cavarzan** [comment]
@konmik The `BasePresenterFragment` doesn't override those methods. 
I've fixed a error in `ViewPager` that was recreating all fragments. I think it solved.
The thing now is `onCreate(Bundle savedState)` in `Presenter` is not called after orientation changes.
I double check your example but I can't see anything that I'm missing =(

**Comment by cavarzan** [comment]
Or `onCreate` is called once and I need to check the state in `onTakeView` ?

**Comment by konmik** [comment]
`onCreate` is called once. This is why we use MVP. :)

You normally do not need to override `onTakeView()` - register restartables during `onCreate` and call them when needed.

**Comment by cavarzan** [comment]
Nice! I think this issue can be closed now. Thanks a lot for your patience.
I using `onTakeView()` now for inject dagger dependencies, since I need the view to call `getComponent` and inject the presenter.

**Comment by konmik** [comment]
The best place for inject presenter dependencies is PresenterPactory, see Ryan's any my answers in https://github.com/konmik/nucleus/pull/12#issuecomment-101777880
