### ISSUE TITLE
Lazy presenter instantiation

### ISSUE THREAD

**Issue by konmik** [konmik/nucleus#19]
To allow easier passing parameters to a presenter factory in some cases.

Origin: https://github.com/konmik/nucleus/pull/12#issuecomment-101777880

**Comment by konmik** [comment]
A piece of cake.

Done!

**Comment by konmik** [comment]
pfff... forgot about support libraries! :D

**Comment by cavarzan** [comment]
@konmik wow that was fast!

**Comment by cavarzan** [comment]
@konmik did you release this enhancement? Thanks.

**Comment by konmik** [comment]
Do somebody need it? :-0 I'll do it now. Wait for 1.3.2 a couple of hours.

**Comment by konmik** [comment]
Have you seen my new library, BTW? https://github.com/konmik/solid

;)

**Comment by konmik** [comment]
Done! Wait a couple of hours and you can grab 1.3.1 version with lazy instantiation

**Comment by cavarzan** [comment]
@konmik thank you very very much!
I didn't see yet, I will take a look!

**Comment by cavarzan** [comment]
@konmik I noticed an error when building with the new version.
`Module version info.android15.nucleus:nucleus-support-v4:1.3.1 depends on libraries but is a jar`

I will take a look if I can solve this... maybe excluding support-v4 can work.

**Comment by konmik** [comment]
So. I was unable to reproduce your problem, I'll try it on a fresh PC later.

Right now I rolled the project back to aar library format, please try 1.3.2 a couple of hours later.
