### ISSUE TITLE
Backfiring pattern?

### ISSUE THREAD

**Issue by jofor** [konmik/nucleus#2]
Imagine this scenario:

	public class LauncherPresenter extends RxPresenter<LauncherActivity> {
		    protected void onCreate(Bundle savedState) {
		        super.onCreate(savedState);

		        SettingsModel settings = Settings.getInstance(view).readSavedSelectedUsageMode();
		        if (settings != null && settings.getMode() != SettingsModel.NONE) {
		            switch (settings.getMode()) {
		                case SettingsModel.ONE:
		                    getView().ShowOnething();
		                    break;
		                case SettingsModel.TWO:
		                    getView().ShowAnotherThing();
		                    break;
		            }
		        } else {
		            getView().ShowSomethingCompletlyDifferent();
		        }
		 	}
		}
Using nucleus i'd imagine you want to handle this from the Presenter. You load a saved setting from your chosen persistence library. Check what setting was loaded and then tell the activity it should show something specific. Now the **problem** here is that this can only take place in the onTakeView()-method of nucleaus, because before that the Activity has not yet been created.

Would it be correct to implement this code in onTakeView? Or would you rather just implement it into the Activity all together? I'd rather keep being consistent in using presenters in all activities.

**Comment by konmik** [comment]
I think that Presenter should not tell view to show something. Presenter in not controller. MVC does not work on Android, see "best practices" section.

I don't know what your Settings object is doing, but it seems to me that you can put all this code into your activity.

**Comment by konmik** [comment]
Yes, you can use onTakeView to push data from presenter to view if that data is needed every time a view is attached.

**Comment by jofor** [comment]
I would think this pattern becomes a little weird. Because this means you should at some cases couple activities with presenters and some not. Else you'll leave empty presenters around for no reason.

Imagine you have an application that has a simple wizard. The only thing that activity should do is present static views and during the wizard maybe write settings that will be saved in your application.

If code such the one above is supposed to be placed in the activity it means i should decouple the presenter for that specific activity, which would break the mvp-pattern.

Does not the mvp-pattern say you should couple: model->presenter->view to display something and the other way around view->presenter->model to store something?

You probably know more than me, but I know this for sure, there will be cases when the presenters will not be used for anything, which strikes me as odd :)

**Comment by konmik** [comment]
Reading preferences is not a task that deserves presenter. This is a one-line main thread action. Keep it stupid simple!

Yes, I use presenter only if I have background tasks to handle or if my database should be split off view. Overengineering is a real problem on big projects, this is why not every view should have them.

**Comment by jofor** [comment]
I'll try stick with that reference :)

**Comment by konmik** [comment]
You can create an observable from preferences if you wish and use deliver() to send data to view.

**Comment by jofor** [comment]
If one is to be able to make a baseclass that makes easy interaction with both activities not using presenters and activities using presenters, I think a new annotation would have to be added in that case :)

if RequiresPresenter-annotation is used to tell that an activitiy needs a presenter, then it should be possible to also tell with an annotation that it does not need it, else you'll have to use two baseclasses for your activities, one that uses nucleusActivity and one that does not :)

**Comment by konmik** [comment]
If you make a project-specific base activity then just don't say that it requires a presenter. :-D

**Comment by jofor** [comment]
Then how will I make a an activity than needs to be extended from that baseactivity that DOES require a presenter? :D

I tried the following 

      public class BaseActivity<PresenterType extends nucleus.presenter.Presenter> extends     NucleusActionBarActivity<PresenterType> {
    }

But if you remove the RequiresPresenter-annotation from the activities extending from it, and I just got an error that I needed to declare a Presenter for the activites using that baseacitivty :)
So that didnt seem to work :)

**Comment by konmik** [comment]
Ok, I will check this. Thank you for the report.

**Comment by konmik** [comment]
Done! :) 1.1.0
