### ISSUE TITLE
More complex example.

### ISSUE THREAD

**Issue by localhostEU** [konmik/nucleus#22]
First of all - thanks for this gr8 library! It's really osom!
Would be nice to see a more complex example of using Nucleus. For example, let's say we have a Social Network with user profile page (RecyclerView). This page has basic user info (getProfile(id) request), and user's posts (getUserPost(offset) request) which could be lazily loaded. How would you code a Presenter? How would u save/restore RecyclerView state (with deliverLatestCache?))? I'm new to RxJava also and i think this example will help a lot of people to get in MVP much faster!

**Comment by konmik** [comment]
Hi,

I'm thinking about writing an advanced usage article. Complex examples are hard to get (at least for me), but code snippets with good description should be good.

Right now I'm busy with my StackLayout project, but as soon as I will have some time, I will write the article. "Nucleus MVP cookbook" or something.

**Comment by localhostEU** [comment]
This is gr8, thank you!

**Comment by jbeckton** [comment]
Whats the trick to returning the ServerApi.Response back to the presenter rather than the activity?

**Comment by konmik** [comment]
Hi Jesse,

This way we can split background task execution off the activity lifecycle. Activity rotates, pauses, being recreated, but the background task is still executing. After it completes presenter returns the result to a new activity instance.

**Comment by jbeckton** [comment]
It appears that the activity implements the call backs for the async tasks "onItems()". Wouldn't the presenter also have access to the main thread?

**Comment by konmik** [comment]
A presenter should return data in the main thread. 

Nothing is stopping you from making additional steps in a presenter it you need to prepare data. You can prepare it in the background or in the main thread.

**Comment by konmik** [comment]
I can give you a better advice if you provide me a more specific task description.
