### ISSUE TITLE
getview is null

### ISSUE THREAD

**Issue by parkjaeiek** [konmik/nucleus#23]
hello

i use this lib

if press phone home key 
and netowrk thread run
call getView() is null....

why getview() null?
i want background thread run and ui change

ps : sry im not write english very well...

**Comment by darxval** [comment]
I believe a ui update can only run on the main thread and if you are at the home screen the window is not attached and can't be updated.

**Comment by parkjaeiek** [comment]
no
ui update is getview() call update
activity onPause after 
presenter is dropview method 
view = null;

why onPause after dropview method is view = null; ?

**Comment by konmik** [comment]
@parkjaeiek hi, can you give me an example that reproduces your problem?

@darxval is right, getView() should not be null between onResume()/onPause() and all view updates must be in the main thread.

**Comment by parkjaeiek** [comment]
@konmik 
hi example code

@RequiresPresenter(MainPresenter.class)
public class MainActivity extends NucleusAppCompatActivity<MainPresenter> {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        getPresenter().test();
    }

    public void testToast(){
        Toast.makeText(this, "hello nucleus", Toast.LENGTH_SHORT).show();
    }
}

public class MainPresenter extends RxPresenter<MainActivity>{

    public void test(){
        Handler handler = new Handler();
        handler.postDelayed(new Runnable() {
            @Override
            public void run() {
                getView().testToast();
            }
        }, 3000);
    }
}

example handler but original source file is retrofit network..

main activity start before 3 second user home button click 

main activity state onPause 

and getview() is null

**Comment by darxval** [comment]
You can not guarantee the main window is attached esp in a post execute you have to wrap your post handler method to ensure the is not destroyed with isDestroyed()  before you call the toast method. The handler will run regardless of the life cycle so you have to be careful

**Comment by parkjaeiek** [comment]
@darxval 
yes i know
this source only test sample code 
and activity is not destroy only pause state...

**Comment by konmik** [comment]
Hi @parkjaeiek 

If your activity is on pause then getView() should be null. This is intended behavior.

If you look at sources, you'll see:

    @Override
    protected void onResume() {
        super.onResume();
        helper.takeView(this);
    }

    @Override
    protected void onPause() {
        super.onPause();
        helper.dropView(isFinishing());
    }

I.e. you can access an activity from your presenter only when the activity it is not paused.

In `Nucleus` we solve this problem of inavailability of views by using `deliver()` method and its variants, see example: https://github.com/konmik/nucleus/blob/master/nucleus-example/src/main/java/nucleus/example/main/MainPresenter.java#L44

Anyway, the question of detaching between onPause/onResume is open. Google recommends to stop all actions during onPause. By detaching a presenter onPause we're letting it know that it should stop CPU/battery-consuming tasks. I never had a real use case for this, but I easily can imagine a couple.

If you have any thought on *why* we should (or not) detach a presenter onPause, I would like to hear from you.
