### ISSUE TITLE
Version 1.3.1?

### ISSUE THREAD

**Issue by phishboh** [konmik/nucleus#24]
First, thanks a lot for your work on nucleus.

It seems that master holds version 1.3.1, whereas "only" 1.3.0 is available using Gradle. When can we expect to see the new version available as a library from Gradle?
Thanks!

**Comment by konmik** [comment]
Hi, 1.3.1 changes are insignificant (mostly internal code reorganizations), so I do not plan to release it yet. The number 1.3.1. is just to differentiate it from the published version.

I'll release 1.3.1 when amount of changes will have any influence on

**Comment by phishboh** [comment]
OK.
Just for your information, I checkout out master and it complained about
compile 'info.android15.nucleus:nucleus:1.3.1'
in
[...]/nucleus/nucleus-support-v7/build.gradle

I just wanted to experiment a little with your example using fragments and have it extend NucleusActionBarActivity instead of NucleusActivity. I got it to work with the sources in master, but not with 1.3.0. There was something about setPresenterState, but I didn't dig more into that. For now I'm perfectly fine with experimenting using the source code in master, and I hope it will work when the new version is available using Gradle.

**Comment by konmik** [comment]
I've tried to build yesterday, but it looks like google broke something again in their build system.

Did you read https://github.com/konmik/nucleus/blob/master/HOWTOBUILD.md ?

**Comment by phishboh** [comment]
Thanks for your support, I'm fine for now.
