### ISSUE TITLE
Nucleus 2.0.0

### ISSUE THREAD

**Issue by konmik** [konmik/nucleus#30]
Is currently under testing.

I hope that it will be production-ready in the middle of August.

Want to join beta?

``` groovy
compile "info.android15.nucleus:nucleus:2.0.0-beta8"
```

Primary goals are:
* Make `RxPresenter` to be completely usable without `getView()` - 100% done!
* Replace `OperatorSemaphore` with standard RxJava operators. - 100% done!
* Simplify internal structure: remove *manager* and *helper*. - 100% done!
* Move all tests into unit tests to be testable without device. - 80%.

Update: a little note about the new `rx.Single`. `rx.Single` is awesome and I'm already playing with it. However, creation of additional methods for it will cause much more confusion than advantage (I already implemented this, but dropped the implementation because it just looks bulky, imagine stranger method names like `deliverSingleCache`, `restartableSingleCache`). The right way to handle `rx.Single` in Nucleus is to cast it to `Observable`.

**Comment by passsy** [comment]
interesting how you removed `OperatorSemaphore` :+1:

**Comment by Trikke** [comment]
Going to try this out, looks very promising!

**Comment by cavarzan** [comment]
@konmik, without `getView()`, how can I call the view without using the `restartable` methods?
I was doing something like this: 
       `Observable.just(null).compose(deliver()).subscribe(o -> {
             getView().doStuff();
        });`

Thnks =)

**Comment by konmik** [comment]
Hi, you can do the same but now after `deliver` you will get the View and data bundled into `Delivery` object.

**Comment by cavarzan** [comment]
OK, since `deliver()` was removed, is the `deliverFirst()` that have the same behavior?

**Comment by cavarzan** [comment]
By example: This is the after and the before. 
<img width="810" alt="captura de tela 2015-08-29 as 13 35 30" src="https://cloud.githubusercontent.com/assets/3915288/9563201/edfd88ea-4e52-11e5-858d-28b5758edc1f.png">
<img width="712" alt="captura de tela 2015-08-29 as 13 36 04" src="https://cloud.githubusercontent.com/assets/3915288/9563202/edfdd598-4e52-11e5-9f88-7fb0f1fcbb6f.png">

**Comment by konmik** [comment]
This is how it looks like now:

        add(q
            .updatable(
                Label.TABLE,
                () -> db.query(Label.SELECT_ALL_SQL, Label.fromCursor))
            .compose(this.<SolidList<Label>>deliverLatestCache())
            .subscribe(this.<SolidList<Label>>split(InputView::onLabels)));

**Comment by cavarzan** [comment]
GOT IT!

Thanks again @konmik 

<img width="657" alt="captura de tela 2015-08-29 as 13 52 46" src="https://cloud.githubusercontent.com/assets/3915288/9563314/ef07ea20-4e55-11e5-949a-8d69c4b5e5e7.png">

**Comment by cnnranderson** [comment]
Everything has been going great, and I honestly love how much better things feel in the 2.0 beta release. I have run into one problematic situation though, and was wondering if anyone else had a problem like mine. 

Currently, I have an app with a NavigationView widget, and a TabLayout with child fragments inside of the container fragment. The child fragments all have their own presenter, along with the parent fragment having it's own presenter.

My problem is, whenever I have a configuration change (read: rotation) when that fragment with tabs and child fragments is in view (or have been shown/loaded once), the app will crash due to some error thrown by Nucleus.

The lines it hits are here:

    public void onRestoreInstanceState(Bundle presenterState) {
        if (presenter != null)
            throw new IllegalArgumentException("onRestoreInstanceState() should be called before onResume()");
        this.bundle = presenterState;
    }

Which is found in the PresenterLifeCycleDelegate class (82-86). I'm not quite sure why it's hitting this, from what I've tested (it's been hard to narrow down specifically what is wrong). If more information is need, I'll gladly test anything you request and let you know my findings.

**Comment by konmik** [comment]
Hi, @cnnranderson!

Are you re-attaching the same fragment a second time or you're re-creating them? Or you just create them once and let the fragment manager to manage them?

I've just tried Nucleus with a child fragment and it works fine!
(I never tried child fragments before, but they work! :)

If you need a help, please create a simplest possible example that can reproduce your problem. I normally help during one-two days.

**Comment by konmik** [comment]
BTW, I'm going to release Nucleus 2.0 as soon as your issue will be resolved. It is pretty stable now.

**Comment by cnnranderson** [comment]
Oh, thanks for the quick response! I will try and throw together a basic app/repo demonstrating the problem (hopefully I can reproduce it along the way -- or better yet, not reproduce it and figure out where I went wrong!). 

I am using a fragment pager adapter to create new instances of the fragments. Here is a snippet of the parent fragment class and the pager adapter, if it's relevant at all: 

Parent: https://gist.github.com/cnnranderson/5770141012f80407468f
Adapter: https://gist.github.com/cnnranderson/c865e1da4ad380e4f7d2

Also just out of curiosity, does the parent Activity need to be of type NucleusAppCompatActivity<>?

**Comment by konmik** [comment]
You inherit from Nucleus view classes if you need a presenter.

**Comment by cnnranderson** [comment]
Apologies for the delay. Got a little pre-occupied the past two weeks with other projects. 

I've discovered the reason for the configuration problems lied in when I was injecting my fragments/presenters. Didn't realize I had been injecting in the onAttached method, which it should have been in onCreate. 

I would like to ask, if you ever get a chance, to review for leaks using leakcanary. I'm not sure if it's on my end, if I'm not using restartable's correctly, or if it's the way the presenters work. I keep getting fragment instance leaks from their respective presenters.

**Comment by konmik** [comment]
Hi, I tested for leaks thoroughly. I normally use MAT memory analyzer during development a lot.

I'm not sure if LeakCanary will work properly here - we're doing some background jobs that it can consider to be a leak.

**Comment by cnnranderson** [comment]
Ah okay, that must be it then. Thanks for the heads up.
