### ISSUE TITLE
Passing values between presenters

### ISSUE THREAD

**Issue by Aphoh** [konmik/nucleus#31]
My current predicament is one where an item is selected in activity A, moving to activity B, where the itemId is passed via an intent from activity A to B. Pre-2.0 it was possible to simply execute any call in the onTakeView method getting the itemId from the activity, but now this seems like it would less practical (calling both start and restartable in the onTakeView method seems unnecessary). What is the best practice for passing data between presenters/activities in 2.0?

**Comment by konmik** [comment]
Hi, you can still execute any method in onTakeView.

Presenter is view's internal stuff, that should not exist for any other application component. So, you pass itemId between activities, and then activity requests item related data from its presenter.

**Comment by Aphoh** [comment]
@konmik Ahh I see, that makes much more sense. Good luck on finishing 2.0 by the way, it looks awesome so far!
