### ISSUE TITLE
Nucleus + Dagger 2

### ISSUE THREAD

**Issue by Zeliret** [konmik/nucleus#32]
Hi there!

Thank you for this great library! But I have a little question about usage it along with Dagger 2.
How can I inject my precious arguments in presenter's constructor and do not break functionality of Nucleus?

If I use `@RequiresPresenter(RxMainPresenter.class)`, I can't pass arguments to my presenter. 
If I use `@Inject RxMainPresenter mainPresenter;`, my presenter will not be cached.

Thank you in advance!

Here is some code:
```java
public class RxMainPresenter extends RxAbstractPresenter<RxMainPresenter.View> {
    private final RxInstancesObservable instancesObservable;

    @Inject
    public RxMainPresenter(final ExecutorService executorService, final RxInstancesObservable instancesObservable) {
        super(executorService);
        this.instancesObservable = instancesObservable;
    }

    @Override
    protected void onCreate(final Bundle savedState) {
        super.onCreate(savedState);

        Observable.create(instancesObservable)
                .retry(3)
                .subscribeOn(Schedulers.from(executorService))
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe(new Subscriber<CabinetInstance[]>() {
                    @Override
                    public void onCompleted() {

                    }

                    @Override
                    public void onError(final Throwable e) {
                        getView().displayInstancesError(e);
                    }

                    @Override
                    public void onNext(final CabinetInstance[] instances) {
                        getView().displayInstances(instances);
                    }
                });
    }

    public interface View extends RxAbstractPresenter.View {
        void displayInstances(final CabinetInstance[] instances);

        void displayInstancesError(final Throwable throwable);
    }
}
```

**Comment by konmik** [comment]
Hi,

With Nucleus 1.x.x you need to override View's getPresenterFactory like this:


    @Override
    public PresenterFactory<PresenterType> getPresenterFactory() {
        final PresenterFactory<PresenterType> superFactory = BaseScreenView.super.getPresenterFactory();
        return superFactory == null ? null : new PresenterFactory<PresenterType>() {
            @Override
            public PresenterType createPresenter() {
                PresenterType presenter = superFactory.createPresenter();
                ((PresenterInjector)getContext()).injectIntoPresenter(presenter);
                return presenter;
            }
        };
    }

With Nucleus 2.0 things became a little bit different:

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        final PresenterFactory<P> superFactory = super.getPresenterFactory();
        setPresenterFactory(new PresenterFactory<P>() {
            @Override
            public P createPresenter() {
                P presenter = superFactory.createPresenter();
                ((Injector) getApplication()).inject(presenter);
                return presenter;
            }
        });
        super.onCreate(savedInstanceState);
        Icepick.restoreInstanceState(this, savedInstanceState);
        ((Injector) getApplication()).inject(this);
    }

**Comment by konmik** [comment]
There is also one link that can help you to deal nicely with Dagger 2: https://gist.github.com/konmik/6ac725fa7134402539c4

**Comment by Zeliret** [comment]
It works! Many thanks, especially for the gist! :)

**Comment by yankeppey** [comment]
I would recomment to use  setPresenterFactory(factory == null ? null : () -> {
 +            P presenter = factory.createPresenter();
 +            App.getInjector().inject(presenter);
 +            return presenter;
 +        });

**Comment by yankeppey** [comment]
setPresenterFactory(factory == null ? null : () -> {
 +            P presenter = factory.createPresenter();
 +            App.getInjector().inject(presenter);
 +            return presenter;
 +        });
