### ISSUE TITLE
return onActivityResult, presenter getView() is null

### ISSUE THREAD

**Issue by jam0cam** [konmik/nucleus#35]
Hi, Not sure if this is an issue, or I just don't know the correct way to handle this.

In my MainActivity, I fired: startActivityForResult()...
Then onActivityResult() comes back, and I do stuff with my presenter. getPresenter() is fine, but within my presenter, getView() returns null.

Some logging tells me this is the flow: 

onResume
startActivityForResult
onPause
onActivityResult
onResume
....

Thanks,
Jia

**Comment by konmik** [comment]
Hi! This is looks like the intended behavior for 1.3.3 but I'm going to change this for 2.0.0.

I will need to make some additional tests, probably tomorrow.

**Comment by konmik** [comment]
So, I've made some tests.

1. This is the intended behaviour for 1.3.3. In 1.3.3 Presenter is connected to the view only between onResume/onPause. So if you need to send something to the view you need to wait until it became available `onTakeView` OR use RxPresenter's `deliver` capabilities.

2. Right now I'm creating an update for 2.0.0 to make start/result scenario reliable even in the case of a process restart. This should work from 2.0.0-beta6, probably tomorrow.

**Comment by konmik** [comment]
If you need to return some data from the presenter immediately then you can just create a function that returns a value in the presenter.

**Comment by jam0cam** [comment]
I ended up doing this and seems to work: 

```java
  protected void onActivityResult(int requestCode, int resultCode, Intent intent) {
       
                getPresenter().takeView(this);
                getPresenter().doXYZ();
      
    }
```
