### ISSUE TITLE
Inject presenter with Dagger

### ISSUE THREAD

**Issue by mheras** [konmik/nucleus#36]
Hello! 

Is it possible to inject the presenters into the activities with Dagger instead of using the `@RequiresPresenter` annotation?

Thanks,
Martin

**Comment by konmik** [comment]
Hi,

No, there are some lifecycle considerations that prevent us from having presenters as singletones. Dagger reuses singletons for each view instance, so there are cases when the same view is instantiated twice, but only one presenter exists. This is causing bugs and lifecycle problems.

The solution is that works in Nucleus is that each presenter should have its own unical id that is saved into view's bundle. This is (almost) impossible to do with Dagger.

But! You're still able to inject stuff into Presenter, take a look at: https://github.com/konmik/nucleus/issues/32

**Comment by mheras** [comment]
Yes, I saw the example with tests. But I would like to avoid using
PowerMock if possible. Do you have any idea? Thanks you!

On Tue, Aug 25, 2015 at 10:14 AM, Konstantin Mikheev <
notifications@github.com> wrote:

> Hi,
>
> No, there are some lifecycle considerations that prevent us from having
> presenters as singletones. Dagger reuses singletons for each view instance,
> so there are cases when the same view is instantiated twice, but only one
> presenter exists. This is causing bugs and lifecycle problems.
>
> The solution is that works in Nucleus is that each presenter should have
> its own unical id that is saved into view's bundle. This is (almost)
> impossible to do with Dagger.
>
> But! You're still able to inject stuff into Presenter, take a look at: #32
> <https://github.com/konmik/nucleus/issues/32>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/konmik/nucleus/issues/36#issuecomment-134580630>.
>



-- 
Martín A. Heras
mheras@gmail.com

**Comment by konmik** [comment]
You can just put a package-visible static PresenterFactory to instantiate presenters.

**Comment by vanceanderson41** [comment]
@konmik I have a similar issue wherein:

I am converting an application to use this library and it currently has an instrumented (Espresso) test setup that relies on the espresso test having a reference to the same instance of a mocked presenter injected into views (accomplished with singleton constructor-injected presenters) I am looking to achieve the same capability with Nucleus but am a little hung up how I might accomplish this, as the Activity lifecycle seems abstracted away from (`ActivityTestRule.getActivity()` is null until a point after which its onCreate has already been called) and curious if you have any thoughts on how one might test Nucleus views isolated from presenter logic?
