### ISSUE TITLE
Looking for an example of how to use deliver*

### ISSUE THREAD

**Issue by twig** [konmik/nucleus#37]
These look very handy and sounds like what I need in my app, but trying to find an example of how to use it is tricky.

**Comment by konmik** [comment]
Hi, I'll make a couple of examples soon.

**Comment by twig** [comment]
Got it working and I love it!

Example:

    ServerAPI.ping()
        .subscribeOn(Schedulers.newThread())
        .observeOn(AndroidSchedulers.mainThread())
        .compose(deliver())
        .subscribe(new Observer<Object>() {
            // ...
        });

**Comment by konmik** [comment]
nice :)

**Comment by konmik** [comment]
You can also write like this to preserve the type information:

            .compose(this.<Account>deliverLatestCache())

**Comment by twig** [comment]
Interesting, didn't know that was valid syntax in Java. Thanks for that!
