### ISSUE TITLE
when view onresume，rxpresenter will onNext again

### ISSUE THREAD

**Issue by jiechic** [konmik/nucleus#38]
a view contain a list，list have add more data interface
I use Rxpresenter，when getData in backgroud，then i offen lock screen and open screen，then presenter would try view.onNext again，then view will be add more the same data。
can you change onNext will call once again for list then load more？

**Comment by jiechic** [comment]
I know how to do.
I create a list in presenter for save data，rxpresenter use this list object for change view data。
then I use my backgound too update this list object。

**Comment by konmik** [comment]
Hi, 

If you're using *cache* delivery type just clear the list before updating it. This is easy, theckout my example: https://github.com/konmik/nucleus/blob/master/nucleus-example/src/main/java/nucleus/example/main/MainActivity.java#L57.

if you're talking abut *replay* delivery and paging.

I normally attach a page number to the each pack of items. 

When View receives items, it checks if the page number = 0, then it resets the current adapter to the new list.
