### ISSUE TITLE
getPresenterFactory not called in fragment - v2.0.0-beta8

### ISSUE THREAD

**Issue by cavarzan** [konmik/nucleus#39]
Overrides to `getPresenterFactory()` is not called in version 2.

``` java
    @Override
    public PresenterFactory<NetworkListPresenter> getPresenterFactory() {
        return new PresenterFactory<NetworkListPresenter>() {
            @Override
            public NetworkListPresenter createPresenter() {
                return presenter;
            }
        };
    }
```

This is working only by setting manually the presenter via `setPresenterFactory`:

``` java
    @Override
    protected void inject() {
        getComponent(SetupNetworkComponent.class).inject(this);
        setPresenterFactory(new PresenterFactory<NetworkListPresenter>() {
            @Override
            public NetworkListPresenter createPresenter() {
                return presenter;
            }
        });
    }
```

**Comment by konmik** [comment]
Now you need to use `setPresenterFactory`! :)

I need to write a better demo, I think.

**Comment by konmik** [comment]
@Override
    protected void onCreate(Bundle savedInstanceState) {
        final PresenterFactory<PresenterType> superFactory = super.getPresenterFactory();
        setPresenterFactory(superFactory == null ? null : () -> {
            PresenterType presenter = superFactory.createPresenter();
            ((Injector)getApplication()).inject(presenter);
            return presenter;
        });
        super.onCreate(savedInstanceState);
    }
