### ISSUE TITLE
getPresenter() null during activity onCreate()

### ISSUE THREAD

**Issue by twig** [konmik/nucleus#40]
Is this by design?

**Comment by konmik** [comment]
Hi, you probably forgot to annotate the view class with `@RequiresPresenter` annotation.

**Comment by twig** [comment]
Ahh yep.

So should Presenter.getView() be null during Presenter.onCreate() ?

**Comment by konmik** [comment]
Yes. It is non-null only between onResume/onPause.

**Comment by konmik** [comment]
I'll add an exception for such this case.
