### ISSUE TITLE
An exception should be thrown if super.onTakeView() is not called

### ISSUE THREAD

**Issue by Aphoh** [konmik/nucleus#41]
Much like how an Activity will throw an exception if super.onCreate(bundle) is not called, a presenter should do the same if super.onTakeView(view) is not called. Failing to call the super method means that no deliver*() calls will ever hit onNext(). For an such easily missable mistake with such a large impact, it seems reasonable to just throw an exception instead of failing silently. Thoughts?

**Comment by konmik** [comment]
OK, I'll do this.

**Comment by dimsuz** [comment]
Also there are `@CallSuper` annotations in app support now. Adding these could make Android Studio emit a warning while editing. If I'm not mistaken this library already depends on support library, so those can be added.

**Comment by mheras** [comment]
+1 `@CallSuper`!
BTW, great library!!!!!
