### ISSUE TITLE
Issue with Paging Example

### ISSUE THREAD

**Issue by Trikke** [konmik/nucleus#45]
I was going through [Paging Example](https://github.com/konmik/nucleus/wiki/Paging-example) and implemented it but it never did more then one extra page request. I noticed the following snippet in `RxPager`.

```java
 public Observable<Integer> pages() {
        return requests
            .concatMap(targetPage -> targetPage <= requestedCount ?
                Observable.<Integer>never() :
                Observable.range(requestedCount, targetPage - requestedCount))
            .startWith(Observable.range(0, initialPageCount))
            .doOnNext(it -> requestedCount = it + 1);
    }
```
The logic seems to handle the case if you would try to request the same page number over and over again.
Shouldn't `Observable.<Integer>never()` be replaced with `Observable.<Integer>empty()`? If a `requestNext(page)` is fired multiple times (as can happen if you don't block it in `OnScrollPaging`, the `Observable.<Integer>never()` will seem to block the stream and no more valid requests will seem to get fired anymore. I replaced it with an empty Observable and then everything seems to work fine.

Can you give me your thoughts on this?

**Comment by konmik** [comment]
Wow, a nice catch! :) Thanks for your issue report. I didn't check the version of paging example that I have on wiki with large data sets. I need to update my tests.
