### ISSUE TITLE
Using RxBinding with Nucleus

### ISSUE THREAD

**Issue by Trikke** [konmik/nucleus#47]
This is more of a general question than an issue.

I wanted to use ```RxView.clicks() ```from the RxBinding library inside an ```RxPresenter```. Because the ```RxPresenter``` has the handy ```add(subscription)``` method, it seemed fitting to write something in ```onTakeView()``` like

```
add(RxView.clicks(getView().getActionReload()).subscribe(new ReloadSubscriber()));
```

But then i noticed the subscription will only get auto-destroyed if ```onDestroy()``` in ```RxPresenter``` is called. But this is not the case when you rotate the device, because the presenter is cached and so any subscriptions are not cancelled. This would leak the Activity through the listener which is added with ```RxView.click()```.

I would like to hear your input on how to use Nucleus with Observables that are tied to their Activities.

**Comment by konmik** [comment]
Hi,

you should not access View internals from Presenter (setup direct callback to View internal parts directly, read edittext values, etc). Always presume that you're dealing with a View interface which returns and accepts only raw data (POJOs, AutoParcel objects, basic values, etc).

Do all bindings inside of View. This is the idea behind MVP - View and Presenter should be separated. You can't obviously separate two things if they depend on each other's dependencies.

**Comment by Trikke** [comment]
Forgot to close this, thank you for the answer!
