### ISSUE TITLE
PresenterStorage.INSTANCE leaks Activity

### ISSUE THREAD

**Issue by sreejithraman** [konmik/nucleus#50]
I can't tell if this is just my code or if it's something to do with Nucleus but I have LeakCanary attached to my app and I am noticing that PresenterStorage.Instance is  leaking my activity. This was the trace that was provided:

* ui.view.SignUpActivity has leaked:
* GC ROOT static nucleus.factory.PresenterStorage.INSTANCE
* references nucleus.factory.PresenterStorage.presenterToId
* references java.util.HashMap.table
* references array java.util.HashMap$HashMapEntry[].[10]
* references java.util.HashMap$HashMapEntry.key
* references ui.presenter.SignUpPhotoFragmentPresenter.view
* references ui.view.SignUpPhotoFragment.mFragmentManager
* references android.support.v4.app.FragmentManagerImpl.mActive
* references java.util.ArrayList.array
* references array java.lang.Object[].[2]
* references ui.view.SignUpUsernameFragment.continueButton
* references android.support.v7.widget.AppCompatButton.mContext
* leaks ui.view.SignUpActivity instance

It seems to be the Nucleus library that is leaking the activity. Would you be able to shed more light into the issue? Let me know if you would like more details.

**Comment by konmik** [comment]
Hi @sreejithraman,

How does this happen? Can you create a minimum size leaking project?

**Comment by sreejithraman** [comment]
I will create one and post it when I get a chance. But it is a pretty simple app. I have a activity with four fragments. The fragments have a textfield and a button and it usually tends to happen when I have a fragment in the backstack

**Comment by sreejithraman** [comment]
Sorry, I thought I updated you on this issue. But it seems to be incredibly uncommon so I can't reliably recreate this issue.
