### ISSUE TITLE
How to test process restart?

### ISSUE THREAD

**Issue by ShlMlkzdh** [konmik/nucleus#52]
How can we restart the process manually when the app is in the background and make sure that everything works properly? Thanks.

**Comment by AdamCopperfield** [comment]
![image](https://cloud.githubusercontent.com/assets/5401297/11428629/7f4be104-947e-11e5-8006-25b2bb563c96.png)

**Comment by ShlMlkzdh** [comment]
Fantastic. Thank you so much.

**Comment by konmik** [comment]
Another option is to Go to Developer options, set Limit background process to "No background processes". Now you can test it by switching between your app and others.

**Comment by ShlMlkzdh** [comment]
Thank you.
