### ISSUE TITLE
Kotlin support

### ISSUE THREAD

**Issue by rpagyc** [konmik/nucleus#53]
Hi. Thank you for this great lib. I just wonder if it can be used when programming in Kotlin. 
Are there any issues with annotations such as @RequiresPresenter?

**Comment by konmik** [comment]
Hi,

AFAIK, Kotlin is interoperable with Java, so it should work with Nucleus.

I've never tried it myself.

**Comment by rpagyc** [comment]
Thank you for fast reply. I just converted nucleus-example to kotlin, everything works properly.
