### ISSUE TITLE
Timing issue?

### ISSUE THREAD

**Issue by Ph1b** [konmik/nucleus#56]
I have a normal presenter and an activity. In onTakeView the presenter passes a boolean to a method in the activity which sets the drawable of a button to an image on true or to null on false.
 
What happens is that since I switched to nucleus I can see the image for the fraction of a second before it vanishes (when the presenter calls it). 

This causes an annoying visual flicker. How can I fix that? Or is it a bug? I don't use any other threads than the main thread.

**Comment by konmik** [comment]
It looks that you're using `observeOn` whyle you're on the main thread.

**Comment by Ph1b** [comment]
Hm, I explicitly threw rx out here. 

Maybe you can take a look?
[View](https://github.com/Ph1b/MaterialAudiobookPlayer/blob/develop/audiobook/src/main/kotlin/de/ph1b/audiobook/activity/FolderChooserActivity.kt#L204)
[Presenter](https://github.com/Ph1b/MaterialAudiobookPlayer/blob/develop/audiobook/src/main/kotlin/de/ph1b/audiobook/presenter/FolderChooserPresenter.kt#L43)

**Comment by konmik** [comment]
Hm, looks good. Have you tried setting the image inside of Activity's onResume? If it will flicker there then it is obviously not a Nucleus issue.

**Comment by Ph1b** [comment]
Okay, my fault. 

Caused by spinner events firing of later. Thanks for the great library!
