### ISSUE TITLE
DeliverLatestCache & RecyclerView Restoring State Question

### ISSUE THREAD

**Issue by sreejithraman** [konmik/nucleus#57]
I wanted to use a RecyclerView inside my fragment and I noticed that I could use `deliverLatestCache()` to handle restoring state during a config change (like rotation). But I don't want to set the adapter when the fragment is resumed (i.e. coming back to the fragment after navigating away). So from the `onNext` I call this method in my view:

```java
public void setAdapter(List<Item> items){
        if(recyclerView.getAdapter() == null){
            recyclerView.setAdapter(new ItemListAdapter(items));
        }
    }
```
`deliverLatestCache()` will call `setAdapter()` both during rotation and when the fragment is resumed. And since I only want it to set the adapter during a config change, I check to see if recyclerView already has an adapter. If it doesn't I assign it one using the data given back from the Presenter.

I wanted to know if this sort of approach is what you had envisioned when you wrote `deliverLatestCache()` or am I using it wrong?

**Comment by konmik** [comment]
Hi,

The idea is that data normally gets updated on some internal event (pull to refresh, synchronization, etc). So the data-to-view pipeline should be reusable and there should be no difference between sending data once, twice, on each resume, on each recreation, etc.

I may probably change this behaviour in next versions, but I see no reason for doing this. Saving a couple of ms during onResume will come at the cost of slightly increased complexity. When there is no clear advantage I prefer simpler solutions.

**Comment by konmik** [comment]
About your use case. Why don't you want to update adapter on resume? Why do you need to recreate it?

**Comment by sreejithraman** [comment]
In that scenario, it was a non-paging list so it didn't matter if i recreated it. But I guess it is better practice to save a reference to the adapter rather than recreate it every time. 

To follow up on the paging, I had a question regarding `deliverReplay()`. In you paging example, you use `restartableReplay` to spit back the fetched Items to the view. From you documentation it says that this "`keeps all onNext values and emits them each time a new view gets attached.`" I just wanted to clarify on this. Does it emit all items only when a view is attached and otherwise just emits the most recently fetched?

**Comment by BoneDaddy2016** [comment]
> The idea is that data normally gets updated on some internal event (pull to refresh, synchronization, etc).

@konmik How would you go about implementing this (pull-to-refresh, etc.) for something like a Retrofit service Observable? I have approximately the following in my RxPresenter:
```java
public void fetchData(String someInput) {
    final Observable<List<Thing>> getThings = service.getStuff(someInput);

    restartableLatestCache(RESTARTABLE_THINGS,
            () -> getThings
                    .subscribeOn(Schedulers.io())
                    .observeOn(AndroidSchedulers.mainThread()),
            ThingsActivity::onNewData,
            ThingsActivity::onError);

    start(RESTARTABLE_THINGS);
}
```
This is called manually by the user from the view (as it requires user input). As it stands, it works great and caches the data so it doesn't repeat network queries on configuration change, etc. as expected. But what if I wanted to add swipe-to-refresh? How would I "invalidate the cache" here?

Thanks!

**Comment by konmik** [comment]
the only place where `restartableLatestCache` have meaning is `onCreate`

**Comment by BoneDaddy2016** [comment]
Oh, I see - I misunderstood `restartableLatestCache` (and friends). Thanks.
