### ISSUE TITLE
Delivery: Overload instead of @Nullable

### ISSUE THREAD

**Issue by Ph1b** [konmik/nucleus#58]
At the moment its (=Delivery) split function takes two Action2 parameters: One for onNext the other for onError.
If you are not interested in onError you can pass null to that. (do I understand correctly?)

I want to propose to add a simple overload:

````java
public void split(Action2<View, T> onNext) {
    split(onNext, null);
}
````

This would make it clearer and more consistent to RxJava. I generally don't like to study the javadoc of each method to find out what happens when I pass null and find that approach quite error prone.

**Comment by konmik** [comment]
There is already a such method:

https://github.com/konmik/nucleus/blob/master/nucleus/src/main/java/nucleus/presenter/RxPresenter.java#L263

**Comment by Ph1b** [comment]
Damn, I have serious problems understanding on what is going on here.

I have a subject emitting longs. Normally I just subscribe to it and get a long in the subscription.

But when I use deliverLatestCache, I get a Delivery <MyView, Long>
Now I need that long. Therefore I need to call delivery.split( f2completed, f2error ).
The split you referred is not in the Delivery class.

````java
prettyLongSubject
    .observeOn(AndroidSchedulers.mainThread())
    .compose(this.deliverLatestCache<Long>())
    .subscribe {delivery : Delivery<BookShelfFragment, Long> ->

    }

**Comment by konmik** [comment]
There are two splits - they are handy for different cases. First one is `Delivery.split` and another is `RxPresenter.split`.

You may probably need to use `RxPresenter.split` inside of `subscribe`, this is the common case. Just write something like

``` Java
.subscribe(split(
(view, loong) -> view.onLongReceived(loong)
));
```

I can't help you with Kotlin here, but as far as I know, it should have even better generics support than Java.

**Comment by Ph1b** [comment]
Great, thanks!

It would be great to see all these "common cases" in the readme or wiki. Would help to get started!
