### ISSUE TITLE
Nucleus for DialogFragments

### ISSUE THREAD

**Issue by PaulWoitaschek** [konmik/nucleus#59]
I have some DIalogFragments where I want to enforce MVC. Can the library add this functionallity?

I think it should work if all code from Fragment is just copied to DialogFragment as it inherits from it.

**Comment by konmik** [comment]
I've tried to apply the pattern to DialogFragment several times, but decided to not include the implementation into the library.

First, material guidelines advise to not put too much of logic into dialogs.

Second, DialogFragment's lifecycle is even more complicated than fragment's, so creating a reliable implementation is a challenge I don't have time and willingness to have.

You can theoretically create such implementation using copy-pasted code from NucleusFragment, but I would advise you to not do this.
