### ISSUE TITLE
Common pattern for binding model to view in RxPresenter

### ISSUE THREAD

**Issue by PaulWoitaschek** [konmik/nucleus#61]
I am not sure what the best way is to bind to a view.

I always am not sure and have two approaches so far. They are both supposed to do the same thing.

# Approach 1
```java
add(view().flatMap { view -> bookChest.removedObservable().map { Pair(view, it) } }
    .observeOn(AndroidSchedulers.mainThread())
    .subscribe { it.first.bookRemoved(it.second) })
```

# Approach 2
```java
add(bookChest.removedObservable()
    .observeOn(AndroidSchedulers.mainThread())
    .subscribe { view?.bookRemoved(it) })
```

The `removedObservable` is a `PublishSubject`. I am only interested in the emissions while the view exists.

I find Approach 1 kind of hacky-ish. And it creates lots of Pair Objects.

Approach 2 has a serious problem: It throws backpressure exceptions when the subject emits at the start at `observeOn`. I thik this is because the view is being created at that time.
I could add a onBackPressureDrop to Approach 2, but that seems also hacky.

What is a *common pattern* to handle this?

It is written in kotlin but it should be clear what happens. the `view?.bookRemoved...` would translate to a `if (view != null) view.bookRemoved...` in java. The `it` is just short for the single emission.

**Comment by konmik** [comment]
The common pattern is to use restartable methods otherwise you will lose state during a process restart. `Add` method in rxpresenter is only for very specific cases (like steaming events).

**Comment by konmik** [comment]
Your usage pattern may differ a lot. I normally use presenter to control background tasks only. If you want to control views from presenter (a classical MVP/C architecture) you may find it quite hard to implement because of Android lifecycles.
