### ISSUE TITLE
Why no delivery() method?

### ISSUE THREAD

**Issue by Zeliret** [konmik/nucleus#66]
Hi there! 
I don't understand how to implement a case where a data should be delivered without caching (like `PublishSubject` or `EventBus` event). 
For example, I have a `UserAddedEvent` event. I need to handle it in my presenter only if there is a view attached (I can skip it otherwise). 

```
add(userAdded()
    .compose(deliverLatestCache()) 
    .subscribe(split(View::addUser)));
```

**Comment by konmik** [comment]
deliverFirst?

**Comment by konmik** [comment]
Oh, you need to skip it... so unusual. Why do you request the data if you can skip it?

**Comment by Zeliret** [comment]
Well, let me explain... 
I have a singleton manager in the background with a WebSocket connection. The manager sends packets and receives. It normalize the data and prepare it before sending to presenters. 
In the same time presenters receive EventBus events from the manager with a normalized data. A presenter should prepare the data before displaying it. 
Recently I noticed that you marked `getView` as depricated, so I decided to replace my `EventBus` "chat" between the manager and presenters with observables. And here I am. I need to receive a special events (actually a packets via WebSocket) in a presenter. But a packet is actual only while a view is ready. 
There is a chance that I doing the whole thing wrong. May be I should use presenters only for fetching some data from a remote server and keep using `EventBus` to communicate between units.

**Comment by cavarzan** [comment]
@Zeliret If you create a subject and call `onNext` in this subject using `deliveryFirst` as compose function didn't work?

**Comment by konmik** [comment]
OK, understood.

A quick and dirty solution should look like this:

```java
onCreate(bundle) {
    add(myBus()
        .switchMap(event -> view().filter(v -> v != null).map(v -> new Object[]{v, event}))
        .subscribe(objects -> ((View)objects[0]).onEvent((EventType)objects[1])));
}
```

**Comment by konmik** [comment]
Oh, you can use `Pair` instead of `Object[]`.

**Comment by Zeliret** [comment]
@cavarzan actually, If I use `PublishSubject` in combination with a `deliverFirst()` method, only the first event is delivered :D

@konmik thank you for the example. I hope you will consider adding such functionality in the library :3

**Comment by Zeliret** [comment]
I ended up by adding this in my base presenter class: 
```java
class Deliver<T>
            implements Observable.Transformer<T, Delivery<V, T>> {

        private final Observable<V> view;

        public Deliver(Observable<V> view) {
            this.view = view;
        }

        @Override
        public Observable<Delivery<V, T>> call(Observable<T> observable) {
            return observable.materialize()
                             .switchMap(notification -> view.map((Func1<V, Delivery<V, T>>) view1 -> view1 == null ? null : new Delivery<>(view1, notification)))
                             .filter(delivery -> delivery != null);
        }
    }
```

```java
public <T> Deliver<T> deliver() {
        return new Deliver<>(view());
    }
```

I don't sure I did it right but now it works as intended. :)

**Comment by konmik** [comment]
@Zeliret your implementation will likely fire your delivery every screen flip. You need `first()` operator to prevent this, see my example.

**Comment by Zeliret** [comment]
@konmik You are right. I don't understand why the `first()` needed, but yeah the delivery fires only once with it. Thank you!

**Comment by konmik** [comment]
`switchMap` souples each event with everything that comes out of `view()`. `view()` emits next view every time a new View gets attached, so `switchMap` couples the event with several views. 

Your wish was to couple it only if `view()` does exist, so we take only `first()` value out of `view()`. If it null we just show nothing, and if it is not null, we will couple it with the event once. Once because we will get no more than one view after `first()`.

**Comment by Zeliret** [comment]
I see. Thank you for the help!
