### ISSUE TITLE
getView() is null

### ISSUE THREAD

**Issue by kurak38** [konmik/nucleus#68]
Hi,
I am starting with Nucleus and I created basic app (based on example02 from [https://github.com/konmik/konmik.github.io/wiki/Introduction-to-Model-View-Presenter-on-Android](https://github.com/konmik/konmik.github.io/wiki/Introduction-to-Model-View-Presenter-on-Android)
```
@RequiresPresenter(HomePresenter.class)
public class HomeActivity extends NucleusAppCompatActivity<HomePresenter> implements HomeFragment.Listener {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_home);

    }


    public void onItemsNext(){
        Toast.makeText(this,"New items", Toast.LENGTH_SHORT).show();
    }

}
```
```
public class HomePresenter extends RxPresenter<HomeActivity> {

    @Override
    protected void onCreate(Bundle savedState) {
        super.onCreate(savedState);


        getView().onItemsNext();
    }
}
```

So I am receiving null pointer in HomePresenter. Also getView() is marked as deprecated in Android Studio 1.5.1

**Comment by konmik** [comment]
Hi, take a look at

https://github.com/konmik/nucleus/blob/master/nucleus/src/main/java/nucleus/presenter/Presenter.java#L120

**Comment by kurak38** [comment]
Right, so that example is not 100% correct because you should use getView() in onCreate and the code should be moved to onResume

**Comment by konmik** [comment]
Which one example?

You can use a presenter from an activity from onCreate to onDestroy, but you can access the activity form presenter only between onResume onPause.

**Comment by kurak38** [comment]
The example 02 from link. So I should move getView().onItemsNext() to onResume() in the presenter

**Comment by konmik** [comment]
Example 02 does not call getView form onCreate, it is called after the delivery callback.

I need to update the example to nucleus 2 though.

**Comment by kurak38** [comment]
yes, but what if that callback is called before onResume (purely theoretically) then the app will crash.
The update would be nice.

**Comment by konmik** [comment]
The delivery method is intentionally written that way to be called only when view is attached.

I'll update the example in the article this week. Right now you can look into the github example:

https://github.com/konmik/nucleus/blob/master/nucleus-example/src/main/java/nucleus/example/main/MainPresenter.java
