### ISSUE TITLE
Presenter's onCreate not called after activity recreate

### ISSUE THREAD

**Issue by oradkovsky** [konmik/nucleus#69]
Hi. This is either an issue of lib or misuse on my end - can you please take a look. The context:

1. There is activity that hosts fragment.
2. Fragment is using "@RequiresPresenter"
3. First time fragment shows up, I can see presenter's onCreate fired.
4. When hosting activity gets killed and user gets back to it, presenter is instantiated but its onCreate is not called. I'm doing state restoration in onCreate so the behavior impacts me badly. 

Looking into fragment's lifecycle, I'm calling something like getPresenter().initialize(...) in fragment's onCreate and getPresenter().updateViews() in fragment's onResume.

Important to note, I'm not using nucleus for restartables, but rather for mvp.

**Comment by konmik** [comment]
Hi, how do you know that the hosting activity gets killed?

There is no way a presenter is instantiated without it gets `onCreate` call. Probably it just does not get destroyed.

**Comment by oradkovsky** [comment]
Added logging into onDestroy of hosting activity. It (activity) does gets destroyed as per log (how I destroy activity: activated "don't keep activities" in emulator's developer options, tap emulator's "home", tap app icon again). One workaround I noticed is adding "getPresenter().destroy();" into, for example, fragment's destroy handlers.

**Comment by konmik** [comment]
I knew it! :dancer: 

When activity gets destroyed this way presenter does not get destroyed. This is one of the reasons why nucleus is build in this specific way.

So when your activity is recreated it attaches itself to the existing presenter and presenter's `onCreate` is not called because is already exists.

**Comment by oradkovsky** [comment]
Assuming presenter already exists, why it's fields are zeroed? At least that's what I'm observing. Anyways, I'll spend some time on another pass of understanding nucleus code, may be will understand the behavior better.

**Comment by konmik** [comment]
Just run debugger. :)

P.S. I normally handle bugs (if there are any reports) during one day. Feel free to write a more detailed report.

**Comment by oradkovsky** [comment]
Thanks, closing,
