### ISSUE TITLE
Examples are not relevant for 2.0.5 version

### ISSUE THREAD

**Issue by lectricas** [konmik/nucleus#70]
Take a look:
Everything is fine for 1.0
![screenshot 2016-02-22 17 20 21](https://cloud.githubusercontent.com/assets/8782219/13219387/d00b759a-d980-11e5-82ac-b2317c1093f3.png)

**Comment by konmik** [comment]
Hi, relevant examples are in the project directory: https://github.com/konmik/nucleus
