### ISSUE TITLE
Any examples of Nucleus in use?

### ISSUE THREAD

**Issue by Orbyt** [konmik/nucleus#72]
I've gone over the examples and read a bit through the source, but would also like to see it used in real projects. I'm currently just setting up an RxPresenter with my NucleusFragments/Activities and just interacting with the presenter through public methods, but would like to try some more advanced features. Does anyone know of any examples of using Nucleus in a full project?

**Comment by konmik** [comment]
Hi, just serach github for `info.android15.nucleus`
