### ISSUE TITLE
Interacting with a model

### ISSUE THREAD

**Issue by Orbyt** [konmik/nucleus#74]
How would you interact with a model (model-view-presenter) using the RxPresenter with nucleus? 

Say you just have some static hardcoded data. Would you just create a new model object to access the data? What is the best practice here?

**Comment by konmik** [comment]
Hi, what does "static hardcoded" mean? If it is just static java data structure then just show it, you don't need MVP to show a constant. :)

**Comment by Orbyt** [comment]
I'm asking what would be best practice. By "hardcoded" I just mean I have some variables i've entered manually with data, eg. `int[] values = {1, 2, 3}`. But lets pretend the data in the model might change. How should this model be interacted with?

In your nucleus example, you do something like this:

```java
App.getServerAPI()
                        .getItems(name.split("\\s+")[0], name.split("\\s+")[1])
                        .observeOn(AndroidSchedulers.mainThread())
```

You call a static method on the "App" class to get your data. This obviously isnt what would normally be done in a real application.

Hope that made sense, let me know otherwise.

**Comment by konmik** [comment]
Normally I inject data accessing objects (network interfaces, database interfaces) into presenters with Dagger. Such interfaces normally provide `rx.Observable` results so I can chain them into `restartableXYZ` method.

Whenever I need to show some data I call presenter to give me that data. Everything is like in the example except instead of `App.getServerAPI()` I use an injected interface.

**Comment by Orbyt** [comment]
Ok, that makes sense. Does nucleus provide any sort of convenience for hooking up the model layer? As in, I can hook up my Presenter to my View using:

 ```java
public class MyPresenter extends RxPresenter<MyFragment>
``` 

and then let the view access the presenter by doing:

 ```java
@RequiresPresenter(MyPresenter.class)
public class MyFragment extends NucleusFragment<MyPresenter>
```

Is there anything cooked into Nucleus to interact with the Model layer in a similar way?

**Comment by konmik** [comment]
Model layer is normally hooked with Dagger injections. https://github.com/konmik/konmik.github.io/wiki/Snorkeling-with-Dagger-2

You just write something like: `Observable<Contact> Database.selectAllContacts()`, inject the `Database` interface into a presenter, and the job is done!

**Comment by Orbyt** [comment]
Ah cool! Thanks for the help, ill give that a thorough read.

Closed.
