### ISSUE TITLE
Possible solution for view recycling and destroying the Presenter in Fragments.

### ISSUE THREAD

**Issue by ShlMlkzdh** [konmik/nucleus#76]
Hi,

In the [View recycling and view stack](https://github.com/konmik/konmik.github.io/wiki/Introduction-to-Model-View-Presenter-on-Android#view-recycling-and-view-stack) section of your [Introduction to Model View Presenter on Android](https://github.com/konmik/konmik.github.io/wiki/Introduction-to-Model-View-Presenter-on-Android), you mention that 

> A fragment can not know if it is detached because of configuration change or because it is being popped off the stack.

I've been trying different ways to solve this issue and came across the [Fragment#isRemoving()](http://developer.android.com/reference/android/app/Fragment.html#isRemoving()) method. I think if we replace `Activity#isFinishing() ` with `Activity#isFinishing()  || Fragment#isRemoving()` then we can destroy the `Presenter` attached to the `Fragment` safely.

@konmik, please let me know if this is a viable solution (at least in the case of a `Fragment`.)

Thanks.

**Comment by konmik** [comment]
Hi @ShlMlkzdh I don't remember how this method is working exactly, probably I already tried it. It looks like the only case this flag is set to true is during FragmentMakager#removeFragment method. I need to try it again.

**Comment by ShlMlkzdh** [comment]
Sounds good. I've tried it a couple times and I think it behaves the correct way. For example, if you replace the current Fragment with another Fragment but add this transaction to the back stack, the isRemoving() method returns false (which is the correct behavior if I'm not wrong since we don't want to destroy the presenter in case the user presses the back button).

**Comment by rlac** [comment]
If you use child fragments, you also need to check isRemoving up the fragment hierarchy - isRemoving is false for a child fragment whose parent (or ancestor further up the hierarchy) is being removed. Only the fragment being removed directly will report isRemoving as true.

I usually end up with a utility method like the following in most of my projects and call it to check whether to destroy a fragment presenter:

`public static boolean isRemoving(Fragment fragment) {
    if (fragment == null) return false;
    else return fragment.isRemoving() || isRemoving(fragment.getParentFragment());
  }`

**Comment by ShlMlkzdh** [comment]
@rlac Thank you. Yeah, I never thought about what happens to child Fragments (honestly, I never use them). Thank you for your solution.

**Comment by konmik** [comment]
Just checked. It works awesome!

I will release a beta version and try it for some time on real projects.

**Comment by ShlMlkzdh** [comment]
Awesome.

**Comment by rlac** [comment]
I think this commit will miss destroying Presenters for Fragment's that are destroyed while on the back stack, as it only does the check during onPause.

My previous comment was going from memory, I looked back at some past projects and I do the check and destroy the Presenter in the Fragment's onDestroy, not onPause.

While a Fragment is on the back stack it's paused, but not removed. It can be removed + destroyed while on the back stack without ever going through another resume/pause cycle (it's onDestroy will always be called though). A couple of cases I know where this can happen if the back stack it's on is destroyed (e.g. replace in a transaction with no addToBackStack) or the Activity is destroyed.

**Comment by konmik** [comment]
I will check this out!

**Comment by konmik** [comment]
It looks like we need to cancel the beta version.  `isRemoving` becomes true even if I put fragment to the back of the stack. So this flag can't tell us when user completely navigates off the fragment.
