### ISSUE TITLE
DialogFragments with Nucleus

### ISSUE THREAD

**Issue by sreejithraman** [konmik/nucleus#79]
I noticed that you mentioned in issue #59 that we shouldn't just copy paste the code for a NucleusFragment into a NucleusDialogFragment. Can you expand onto why you would advise against it. What problems did you run into?

**Comment by konmik** [comment]
I don't remember exactly, there was something with inability to correctly detect dialog cancellation toghether with overall complexity. 

The total amount of lifecycle events = multiplication of all numbers of events for each considered component. In this case the formula becomes something like this: fragment * dialog * dialog view.

**Comment by sreejithraman** [comment]
Did you need to detect dialog cancellation for knowing when to take view?

**Comment by konmik** [comment]
To discard presenter as well. When fragment is removed we need to manually destroy its presenter.

**Comment by sreejithraman** [comment]
Why can we not reliably say that the fragment will be destroyed onDestroy?

**Comment by konmik** [comment]
because after a config change it will be recreated and we will need to attach background tasks to the new fragment instance.

**Comment by sreejithraman** [comment]
Is that behavior different from regular fragments?

**Comment by konmik** [comment]
regularly fragments just lose their background tasks or use dirty things like Loaders
