### ISSUE TITLE
When are variables destroyed in the Presenter lifecycle?

### ISSUE THREAD

**Issue by sreejithraman** [konmik/nucleus#80]
I noticed that my global variable became null by the time it hit the activity's onDestroy

**Comment by duo2005duo** [comment]
@sreejithraman 
I think the variables will be destroyed in the following situation:
1. The user shut down the activity by pressing the button back or calling the method `finsih()`
2. The process is killed

**Comment by konmik** [comment]
Global variables are not affected by nucleus.
