### ISSUE TITLE
PresenterStorage

### ISSUE THREAD

**Issue by ruhaly** [konmik/nucleus#81]
java.lang.NoClassDefFoundError: nucleus.factory.PresenterStorage$1
                                                       nucleus.factory.PresenterStorage$1
                                                       nucleus.factory.PresenterStorage.add(PresenterStorage.java:26)
                                                       nucleus.view.PresenterLifecycleDelegate.getPresenter(PresenterLifecycleDelegate.java:56)
                                                       nucleus.view.PresenterLifecycleDelegate.onResume(PresenterLifecycleDelegate.java:92)
                                                       nucleus.view.NucleusAppCompatActivity.onResume(NucleusAppCompatActivity.java:70)
                                                       com.luichi.ygj.base.BaseActivity.onResume(BaseActivity.java:540)
                                                       android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1192)
                                                       android.app.Activity.performResume(Activity.java:5327)
                                                       android.app.ActivityThread.performResumeActivity(ActivityThread.java:2769)
                                                       android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2808)
                                                       android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2243)
                                                       android.app.ActivityThread.access$800(ActivityThread.java:138)
                                                       android.app.ActivityThread$H.handleMessage(ActivityThread.java:1201)
                                                       android.os.Handler.dispatchMessage(Handler.java:102)
                                                       android.os.Looper.loop(Looper.java:136)
                                                       android.app.ActivityThread.main(ActivityThread.java:5016)
                                                       java.lang.reflect.Method.invokeNative(Native Method)
                                                       java.lang.reflect.Method.invoke(Method.java:515)

**Comment by konmik** [comment]
Probably something wrong with your build configuration?

**Comment by ruhaly** [comment]
系统异常退出11java.lang.NoClassDefFoundError: nucleus.factory.PresenterStorage$1
                                                                    nucleus.factory.PresenterStorage$1
                                                                    nucleus.factory.PresenterStorage.add(PresenterStorage.java:26)
                                                                    nucleus.view.PresenterLifecycleDelegate.getPresenter(PresenterLifecycleDelegate.java:56)
                                                                    nucleus.view.PresenterLifecycleDelegate.onResume(PresenterLifecycleDelegate.java:92)
                                                                    nucleus.view.NucleusAppCompatActivity.onResume(NucleusAppCompatActivity.java:70)
                                                                    com.luichi.ygj.base.BaseActivity.onResume(BaseActivity.java:561)
                                                                    com.luichi.ygj.StartActivity.onResume(StartActivity.java:236)
                                                                    android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1202)
                                                                    android.app.Activity.performResume(Activity.java:5404)
                                                                    android.app.ActivityThread.performResumeActivity(ActivityThread.java:2830)
                                                                    android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2884)


Has not been resolved.
