### ISSUE TITLE
Lifecycle of Presenter in a Fragment has a problem

### ISSUE THREAD

**Issue by hnvn** [konmik/nucleus#84]
In a Fragment, the View is only created (inflate) in onCreateView() method and this View is only destroyed in onDestroyView() method. So, takeView() method of Presenter should place in onCreateView() and dropView() method should place in onDestroyView(). Currently, takeView() method place in onResume() method, it cause events (in restartableLatestCache() method) is emitted every time onResume() method is called despite the View is recreated or not. Example: when I press power button to lock screen, after that unlock, my View isn't recreated but my Presenter still emits event to update UI (eg: a API call), it's not necessary.

**Comment by konmik** [comment]
Hi @hnvn,

I am aware of this issue. The 3.0.0 will have a better lifecycle.

Here is the commit I'm currently testing:

https://github.com/konmik/nucleus/commit/44c7722e32d1d54eb95f126586c79f114c4b14a0

Thanks for the feedback.

**Comment by konmik** [comment]
The reason I prefer to attach presenter during the first `onResume` is that after `onCreate` we have `onRestoreInstanceState` which may break data that was received from presenter during `onCreate`.

**Comment by konmik** [comment]
3.0.0-beta is out

**Comment by hnvn** [comment]
Glad to hear about it!

**Comment by konmik** [comment]
https://github.com/konmik/nucleus/commit/2863995e40d65d144843f91e0e646a5d4be6248d
