### ISSUE TITLE
nucleus.factory.PresenterStorage

### ISSUE THREAD

**Issue by ruhaly** [konmik/nucleus#85]
系统异常退出11java.lang.NoClassDefFoundError: nucleus.factory.PresenterStorage$1
nucleus.factory.PresenterStorage$1
nucleus.factory.PresenterStorage.add(PresenterStorage.java:26)
nucleus.view.PresenterLifecycleDelegate.getPresenter(PresenterLifecycleDelegate.java:56)
nucleus.view.PresenterLifecycleDelegate.onResume(PresenterLifecycleDelegate.java:92)
nucleus.view.NucleusAppCompatActivity.onResume(NucleusAppCompatActivity.java:70)
com.luichi.ygj.base.BaseActivity.onResume(BaseActivity.java:561)
com.luichi.ygj.StartActivity.onResume(StartActivity.java:236)
android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1202)
android.app.Activity.performResume(Activity.java:5404)
android.app.ActivityThread.performResumeActivity(ActivityThread.java:2830)
android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2884)

Has not been resolved.

**Comment by konmik** [comment]
Can't reproduce.

Do you have a minimal example that reproduces this error?

When do you get it?

**Comment by ruhaly** [comment]
some phones has this error,

**Comment by ruhaly** [comment]
They have no memory card

**Comment by ruhaly** [comment]
链接：http://pan.baidu.com/s/1boD5O1x 密码：uiae   
you can down My code

**Comment by konmik** [comment]
On which devices?

**Comment by ruhaly** [comment]
I solved ,thanks!
