### ISSUE TITLE
Nucleus and ViewPager

### ISSUE THREAD

**Issue by aleien** [konmik/nucleus#86]
Hello! 
I was wondering, how and will Nucleus work when used with ViewPager that holds fragments of the same kind. Since there will be several instances of similar Presenters in Presenter Storage, how we ensure that restored fragments get appropriate presenters and states?

**Comment by konmik** [comment]
Hi, when instantiated each presenter gets an UUID and during view restoration a corresponding presenter will be found using its UUID that was saved inside View's bundle.

**Comment by aleien** [comment]
Thank you very much! It's clear now (:
