### ISSUE TITLE
How to handle loading states and requests?

### ISSUE THREAD

**Issue by PaulWoitaschek** [konmik/nucleus#87]
Im still having some issues understanding `restartableLatestCache`.

I have an class that is handling network access and caching. So it has a method `getData(boolean forceFromNetwork)` returning a `Single<Data>`. That `forceFromNetwork` is called when the user pressed a button for retry.

When I enter the view the first time, `getData(forceFromNetwork=false)` should be called.
When the `Single<Data>` starts I want to display a loading state to the view, and when it returns I want to show the data or an error state.
When the user pressed reload, the `getData(forceFromNetwork=true)` should be called with the same behavior.

How can I archive that using nucleus? I experimented with `restartableLatestCache` and `restartable` and using two `restartableId` but I'm a little unsure how to handle it properly. 
Till now I was just extending `Presenter` and added a `CompositeSubscription` between `onTakeView` and `onDropView` to which I was adding and removing the two Singles. But it seems like this library is exactly build so I do not have to worry about this manual starting / stopping.

Maybe it would also be useful to add the `Loading-View-Error` flow to the examples as its one of the most common requirements.

**Comment by inorichi** [comment]
I would always set the loading state during `onCreate`/`onCreateView`, and your `restartableLatestCache` will remove the loading state. It's safe to do it like this because the data won't be delivered until `onResume`.

View (pseudocode):
```
onCreate(boolean savedState) {
    if (savedState == null) {
        presenter.getData(false)
    }
    progressBar.setVisibility(View.VISIBLE)
    retryButton.setOnClickListener { retryData() }
}

onNextData(List<Data> items) {
    progressBar.setVisibility(View.GONE)
    adapter.setItems(items)
}

onDataError(Throwable error) {
    progressBar.setVisibility(View.GONE)
    retryButton.setVisibility(View.VISIBLE)
}

retryData() {
    progressBar.setVisibility(View.VISIBLE)
    retryButton.setVisibility(View.GONE)
    presenter.getData(true)
}
```

Hope it helps

**Comment by konmik** [comment]
This is how I do it:

```
@State boolean isLoading ;

onCreate
   if isLoading 
      showProgressBar
     
   if savedState == null
     showProgreessBar
     isLoading = true
     presenter.getData(forceFromNetwork=false)

onUserRequestedFreshData
     showProgreessBar
     isLoading = true
     presenter.getData(forceFromNetwork=true)

onDataReceived
   hideProgressBar
   showData
   isLoading = false

onNetworkError
   hideProgressBar
   showErrorRetryView
   isLoading = false
```

There is also `isShowingErrorRetryView` flag that need to be saved.

I have `PlaceholderView` class above each screen, it contains sub-screens for loading/network_error_retry_button/empty_result and manages `isLoading`, `isShowingErrorRetryView` flags, so the main view logic is not bloated.

**Comment by konmik** [comment]
But I also liked the @inorichi's answer, it seems valid and shorter.
