### ISSUE TITLE
Use with Conductor...

### ISSUE THREAD

**Issue by sirvon** [konmik/nucleus#88]
Can you give guidance or an example on using this mvp frameworks with [Conductor](https://github.com/bluelinelabs/Conductor)?

Thank you

**Comment by konmik** [comment]
I can not provide you any guidance/best practicies about libraries like this. I tried some of them, I also tried to replace fragments with my own implementations.

This is doable, but why? With Nucleus I only need a couple of lifecycle methods and I do not have troubles with fragments at all so I don't need to replace them.
