### ISSUE TITLE
Multiple presenters per activity

### ISSUE THREAD

**Issue by vinaybn92** [konmik/nucleus#89]
The @RequiresPresenter annotation is not repeatable, but I have multiple presenters in my activity (one for populating a menu dynamically, one for the content, etc). Is there a way I can use nucleus? I really like how it handles config changes.

**Comment by konmik** [comment]
I see three options here: 

1. Join presenters.
2. Split activity into separated views, each with its own presenter.
3. Create a custom base class - just copy-paste NucleusActivity code and have any amount of presenters you wish.

**Comment by vinaybn92** [comment]
I'm looking at the NucleusActivity but can't tell what I need to change to able to accommodate multiple presenters.

**Comment by konmik** [comment]
Copy-paste `presenterDelegate as many times as you need presenters. Give them custom factories.
