### ISSUE TITLE
Lifecycle changes in 3.0.0 causing problems

### ISSUE THREAD

**Issue by gborland** [konmik/nucleus#90]
I'm experimenting with the change from 2.0.6 -> 3.0.0. The lifecycle changes in particular are causing some problems.

### With 2.0.6

1. Presenter calls `restartableLatestCache()`.
1. Presenter starts a long-running background operation.
1. User presses Home button to put the app into the background. (Activity is in the stopped state.)
1. Background operation completes silently.
1. User waits a few more seconds.
1. User switches app back into the foreground.
1. Presenter's callback is called with the cached result of the background operation.
1. Presenter delivers result to activity for display.

This all works perfectly.

### With 3.0.0

1. Presenter calls `restartableLatestCache()`.
1. Presenter starts a long-running background operation.
1. User presses Home button to put the app into the background.
1. Background operation completes (the app is still hidden, and the activity is still in the stopped state).
1. Presenter's callback is called immediately with the result of the background operation.
1. Presenter delivers result to activity for display.
1. Activity gets confused because it's stopped, but is receiving a result for display.

It looks as if this change was intentional, but I don't understand why. It means I now have to add extra logic to my Presenter to establish whether the Activity is visible or not, and then decide if, how and when to deliver the result accordingly.

Can you please clarify what is supposed to happen now?

**Comment by konmik** [comment]
Why don't you want to update activity if it is in the background?

**Comment by gborland** [comment]
Because the activity calls `startActivity` when it received the result, to navigate to a new activity. This should not happen if the app is hidden.

**Comment by konmik** [comment]
Hmm, interesting.

I never had such cases. Usually the problem was opposite - when activity was paused by a popup it didn't update, this was causing some problems and later, when activity was resumed people didn't want to receive results twice on each resume.

I think we somehow need support two delivery modes the same time.

Thank you for the report, I have something to think about now.

**Comment by nbsith** [comment]
Similiar case is when we want to show DialogFragment (like error message). It ends with "Can not perform this action after onSaveInstanceState" exception as we are not allowed to show dialog while being in background.

**Comment by konmik** [comment]
@nbsith Thanks for reporting it. This is weird, because I never had such troubles. I think we will return the lifecycle change back in 4.0 version. I don't know what to do with NucleusView, because it does not have onPause/onResume lifecycle and this makes this behavior a little bit inconsistent.

**Comment by konmik** [comment]
I reverted the lifecycle back in 4.0.0, please try and tell if it works for you now.

**Comment by nbsith** [comment]
As far as activity lifecycyle is concerned change fulfils my needs. I am already using own copy of NucleusFragmentActivity from 3.0 with presenterDelegate.onDropView() moved from onDestroy to onPause.

**Comment by gborland** [comment]
@konmik Works nicely now, thanks. 👍

**Comment by konmik** [comment]
Great!

**Comment by PaulWoitaschek** [comment]
Yup, way better. With the lifecycle changes it caused me lots of bugs where an `Activity` was no longer visible but was still receiving events.
