### ISSUE TITLE
Testing with Dagger 2

### ISSUE THREAD

**Issue by vinaybn92** [konmik/nucleus#91]
I'm looking to use nucleus on a project I'm working on. Currently I'm passing the dependencies to my presenters using constructor injections which makes mocking these dependencies and testing the presenter very easy. Is there anyway to use this testing approach with nucleus?

**Comment by vinaybn92** [comment]
For now I'm going to make my presenter as thin and dumb as possible(if event is loading, content, timeout or error then call appropriate method on the view) and extract all logic into use cases so I don't need to test my presenter.

**Comment by konmik** [comment]
Hi, I sometimes test presenters of if they have some complicated logic - calling several network apis, events streaming etc. You can of course inject test dependencies, there is nothing that prevents you, see the testing example.

**Comment by vinaybn92** [comment]
The main advantage of MVP is unit testing but Nucleus complicates that a bit, especially when compared to other MVP platforms, but I love how it simplifies persisting subscriptions. I was just wondering if there was a way to write some quick unit tests with little boilerplate. I think it's best to extract most of the logic from the presenter and put it in it's dependency and test that instead.
