### ISSUE TITLE
If I have multiple restartableLatestCache, is there an order in which it updates 

### ISSUE THREAD

**Issue by sreejithraman** [konmik/nucleus#92]
Let's say i have a `restartableLatestCache` that fetches items from the db to set the view and then i make a call to the server to get the latest version of one of the items. Will I be guaranteed that when the activity is recreated (like after rotation) that the db cache updates the view and then the server cache updates the view?

**Comment by konmik** [comment]
It will just re-push the latest result to a new view. It does not care where the data came from (db, network, cache, etc)

**Comment by sreejithraman** [comment]
That wasn't what I was asking. I must have worded the question badly. I was asking if the order would be guaranteed when re-pushing. If there are two `restartableLatestCache`, will they re-push in the same order as I started them?

**Comment by konmik** [comment]
No, the order is not guaranteed. You may probably need to join these two restartables into one request or deal with it somehow on the view side.
