### ISSUE TITLE
getView is deprecated

### ISSUE THREAD

**Issue by wisien92** [konmik/nucleus#93]
I have a simple presenter (learning MVP) with a runnable. Inside runnable I want to call method from activity to update view. I saw that getView is deprecated so I looked examples in repository and I tried 
using Action1 - but the view is not updated (when I was not using nucleus library it worked so I just need to figure out how to call activitie's methods).

Below is my code:

`public class MainPresenter extends RxPresenter<MainActivity> {

	private final int interval = 1000; // 1 Second
	private Handler handler = new Handler();
	private Runnable runnable = new Runnable() {
		public void run() {
			new Action1<MainActivity>() {
				@Override
				public void call(MainActivity activity) {
					activity.updateProgressBar();
				}
			};

			StartTimer();
		}
	};

	@Override
	protected void onCreate(Bundle savedState) {
		super.onCreate(savedState);
		StartTimer();
	}

	public void StartTimer() {
		handler.postAtTime(runnable, System.currentTimeMillis() + interval);
		handler.postDelayed(runnable, interval);
	}
}`

`getView()` works - but is deprecated so I dont want to use it.

PS: sorry for incorrect code styling but somehow I could not get first and last line to be formatted

**Comment by konmik** [comment]
Hi @wisien92 

I `getView` is deprecated when you're using it from `RxPresenter`. If you're going the RxJava path, you must combine your data with `view()` observable, see "deliver" methods.

If you're not using RxJava then just stick with plain old `Presenter` which provides no-rx functionality you may want.

**Comment by wisien92** [comment]
Ok I want to go RxJava path - and I am learning how restartables/observables work. But what If there is some simple action that I want to perform only once (eg. at start of activity) and I do not want to register restartable (since it wont be restarted). How can I call activities funtion? Is it possible using deliver methods? Or I just shouldn't do that since it's against Rx principals?

**Comment by konmik** [comment]
Any background task can be interrupted by android, even those you make one time. So I recommend to make them restartable as well. Non-restartable tasks are those which can not be comleted, for example message streams or something like that.

**Comment by Gustorn** [comment]
I came across the `getView()` is deprecated message recently while trying to do the following action:

1. Button click on `View`
2. Building an `Intent` on the `Presenter`
3. Start a new activity using the View's `Context`

I came up with this solution (excuse the Kotlin code): 

```kotlin
restartableFirst(2, { Observable.just(Unit) }, {
    view, it -> view.startActivity(Intent(view.context, ReviewsActivity::class.java))
})
```

But it feels like a hack. Is there an idiomatic way to perform one-shot actions without using any deprecated methods?

**Comment by konmik** [comment]
@Gustorn the idiomatic way is to not control views from presenter. 

User controls Android, Android API controls Activities, Activities control Views, Views control Presenters, Presenters control Data requests, Data requests control Data. 

Doing the opposite is asking for troubles.

**Comment by TWiStErRob** [comment]
@konmik so how/where do you start an activity (@Gustorn's code)? It must be some lower layer calling Android API in your chain, the decision to do so is likely in the Presenter or upon model change.

**Comment by konmik** [comment]
@TWiStErRob decisions should be made on the top layer (View). When you try to push some decisions down you get troubles - ping-pong logic between layers, NPEs because lower layers did not expect nulls, etc.
