### ISSUE TITLE
Why not do all this background processing in a Service?

### ISSUE THREAD

**Issue by sirvon** [konmik/nucleus#98]
What was the thinking behind not doing all the background processing in a service?

**Comment by konmik** [comment]
Which problems such solution could solve?

**Comment by sirvon** [comment]
From reading the comments it seems most ppl are attempting to get data from db or external service then bring it into ui using rx principles, what's the advantage of not doing that in an intent or foreground service. The problems that this library solves is mostly about orientation change?

**Comment by konmik** [comment]
Yes, Nucleus is about building better UIs that have background tasks attached.

If someone needs a service he can just use plain service, I don't see any things that need to be improved there. Services have some boilerplate code attached, but nothing that needs special treating.

**Comment by sirvon** [comment]
The presenter is where the ui attached background processing is being done right? So the presenter is where any work would be passed to the service right? Also if the service was listening to some incoming data it would pass it to the presenter, which would pass it to the ui/view right? ...I'm kinda trying to figure out where services play in. How to access the presenter from a service. Thanks.

**Comment by konmik** [comment]
I don't see how presenter is connected with services in your logical sequence.

*Sometimes* it is a good idea to connect a presenter with a service, in this case an intermediate singleton should be used. I normally inject a such singleton using Dagger, so everything is testable and nice.

But services should not be used for each background task, there is simple no reason to do so. Service is a class with complicated starting rules, it requires to write tons of code, and it can't be persisted into a bundle. Usually a background task is a couple of lines of code and it is trivial to persist such task argument into a bundle, this is what Nucleus is doing.
